### ISSUE TITLE
Criar método de editar o Funcionario

### ISSUE THREAD

**Issue by danilofsti** [tc100/hestia-planning#15]

**Comment by antunesbe** [comment]
@danilofsti @TalitaFanelli 
favor testar o editar do do funcionario e comentar aqui oque acham

**Comment by antunesbe** [comment]
Falta:
* mensagem que foi editado
* continuar mostrando os dados do funcionario

**Comment by danilofsti** [comment]
Tela de edição redirecionando para ela mesma apos salvar o registro!

**Comment by danilofsti** [comment]
Mudado para redirecionar para o index de funcionarios
Mensagem de edição aparecendo 
Mensagem de fail criada (não testada)
