### ISSUE TITLE
Melhorar pagina de detalhes do funcionario

### ISSUE THREAD

**Issue by antunesbe** [tc100/hestia-planning#22]

**Comment by danilofsti** [comment]
@antunesbe @TalitaFanelli a ideia do detalhamento era para ser um modal, não tinha dado tempo (não lembrava como fazer) 
você clica no botão e aparece um 'popup(?)' com os detalhes, vc clica fora ou no x e ele fecha por isso está simples, precisa fazer um script para chamar da tela index, vou procurar esse fds

**Comment by TalitaFanelli** [comment]
Bom, vou tentar fazer amanhã... achei esses liks:

https://www.youtube.com/watch?v=3phA5y0Oj3A


http://www.tutorialrepublic.com/twitter-bootstrap-tutorial/bootstrap-modals.php#modal-events


http://www.w3schools.com/bootstrap/bootstrap_ref_js_modal.asp


http://dagatech.com/criando-uma-janela-modal-com-bootstrap/


http://globocom.github.io/bootstrap/javascript.html
